name: Regenerate Diagram

on:
    push:
        branches:
            - main
        paths:
            - 'schema.prisma'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install
        - name: Format schema.prisma
          run: npx prisma format
        - name: Generate Prisma diagram
          run: npx prisma generate

        - uses: EndBug/add-and-commit@v9
          with:
            author_name: github-action-bot
            author_email: github-action-bot@users.noreply.github.com
            message: "Update `ERD.svg`, format `schema.prisma`"
            add: './'