name: Regenerate Diagram

on:
    push:
        branches:
            - main
        paths:
            - 'schema.prisma'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        - name: Install dependencies
          run: npm install

        - name: Generate Prisma diagram
          run: npx prisma generate

        - name: Commit and push changes
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add ERD.svg
            git commit -m "Regenerate Prisma diagram" || exit 0
            git push